service: wrap-and-pub

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    TOPIC_NAME: t1-${opt:stage, self:provider.stage}
    QUEUE_NAME: q1-${opt:stage, self:provider.stage}
    TOPIC_ARN: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:t1-dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: ${self:provider.environment.TOPIC_ARN}
  apiKeys:
    - wp-api-keyi-${opt:stage, self:provider.stage}
  usagePlan:
    throttle:
      burstLimit: 10
      rateLimit: 1

functions:
  wrapPub:
    handler: wp.wrapPub
    events:
      - http:
          path: wp/{topic}
          method: post
          private: true
  
  logProcessor:
    handler: logprocessor.handler
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/wrap-and-pub-${opt:stage, self:provider.stage}-wrapPub'
          filter: 'PublishContext'

resources:
  Resources:
    sampleTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: ${self:provider.environment.TOPIC_NAME}
    secondTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: ${self:provider.environment.TOPIC_NAME}-2

 

plugins:
  - serverless-pseudo-parameters