service: wrap-and-pub

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    TOPIC_NAME: t1-${opt:stage, self:provider.stage}
    QUEUE_NAME: q1-${opt:stage, self:provider.stage}
    TOPIC_ARN_BASE: 'arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: ${self:provider.environment.TOPIC_ARN_BASE}*
  apiKeys:
    - wp-api-keyi-${opt:stage, self:provider.stage}
  usagePlan:
    throttle:
      burstLimit: 20
      rateLimit: 10

functions:
  wrapPub:
    handler: wp.wrapPub
    events:
      - http:
          path: wp/{topic}
          method: post
          private: true
  


resources:
  Resources:
    sampleTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: ${self:provider.environment.TOPIC_NAME}
    secondTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: ${self:provider.environment.TOPIC_NAME}-2

 

plugins:
  - serverless-pseudo-parameters