service: loghose

custom:
  stage: ${opt:stage, 'dev'}
  serviceName: loghose
  S3BucketNameForFirehoseDestination: ${self:service}-${self:custom.stage}-firehose-destination


provider:
  name: aws
  stage: dev
  runtime: nodejs12.x

#  iamRoleStatements:
#    - Effect: Allow
#      Action:
#        - sts:AssumeRole

functions:
  transform:
    handler: handler.transform
    name: ${self:service}-${self:custom.stage}-data-transform-lambda
    timeout: 60
  


resources:
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/firehose.yml)}
  - ${file(resources/logs.yml)}

 
plugins:
  - serverless-pseudo-parameters